# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo_ Liver' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo_ Liver

# Keyboard
pod 'IQKeyboardManagerSwift'

# image
pod 'SDWebImage'

# Lottie Animation
pod 'lottie-ios'

end
